import { ProgrammeHOD, LeadershipMember } from '../types';
import { INSTITUTIONAL_LEADERSHIP } from '../data/collegeData';

export const BEC_PROGRAMMES_HODS: ProgrammeHOD[] = [
  // ================= 11 UNDERGRADUATE (B.E.) PROGRAMMES =================
  {
    id: 'ug-civil',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Civil Engineering',
    departmentName: 'Department of Civil Engineering',
    code: 'CV / E031 & E049',
    establishedYear: 1963,
    intake: 120,
    stream: 'Aided (60) & Un-Aided (60)',
    hodName: 'Dr. S. H. Sanni',
    hodDesignation: 'Professor & Head, BoS Chairman',
    hodEmail: 'cv_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Pioneering foundational engineering since 1963 with cutting-edge testing in structural dynamics, geotechnical engineering, environmental engineering, and GIS mapping.',
    specializations: ['Structural Dynamics & Earthquake Engg', 'Geotechnical & Soil Mechanics', 'Environmental Hydraulics', 'GIS & Geoinformatics'],
    keyLabs: ['Total Station & Geoinformatics Lab', 'Advanced Concrete Testing Lab', 'Soil Mechanics & Geotechnical Lab'],
    keyHighlights: ['NBA Accredited Department', 'Primary consultancy center for irrigation & public works', 'Recognized VTU Research Centre'],
    accreditation: 'NBA Accredited',
    vtuResearchCenter: true
  },
  {
    id: 'ug-mechanical',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Mechanical Engineering',
    departmentName: 'Department of Mechanical Engineering',
    code: 'ME / E031 & E049',
    establishedYear: 1963,
    intake: 120,
    stream: 'Aided (90) & Un-Aided (30)',
    hodName: 'Dr. V. V. Kuppast',
    hodDesignation: 'Professor & Head, BoS Chairperson',
    hodEmail: 'me_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Equipped with sophisticated CAD/CAM/CAE centres, CNC machining, additive manufacturing 3D printers, internal combustion engine testing rigs, and wind tunnel diagnostics.',
    specializations: ['Computer Aided Engineering (CAE)', 'NVH & Vibration Diagnostics', 'Advanced Manufacturing Technology', 'Additive Manufacturing & Composites'],
    keyLabs: ['AICTE IDEA 3D Prototyping Lab', 'Heat Transfer & Thermodynamics Lab', 'CNC Machining & Robotics Lab'],
    keyHighlights: ['Host of prestigious BAJA SAE racing team', 'Significant research in composite materials', 'Consultancy for regional manufacturing hubs'],
    accreditation: 'NBA Accredited',
    vtuResearchCenter: true
  },
  {
    id: 'ug-eee',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Electrical & Electronics Engineering',
    departmentName: 'Department of Electrical & Electronics Engineering',
    code: 'EE / E031 & E049',
    establishedYear: 1963,
    intake: 60,
    stream: 'Aided (30) & Un-Aided (30)',
    hodName: 'Dr. Raghuram L. Naik',
    hodDesignation: 'Associate Professor & Head',
    hodEmail: 'eee_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Founding branch recognized across Karnataka for pioneer work in wind and solar microgrids, power electronics, electric vehicle drives, and smart grid automation.',
    specializations: ['Renewable Energy Microgrids', 'Electric Vehicle Powertrain Drives', 'Power Electronics & FACTS', 'Smart Grid Automation'],
    keyLabs: ['Smart Grid & Renewable Energy Lab', 'Power Electronics & Drives Lab', 'High Voltage Engineering Facility'],
    keyHighlights: ['Wind Energy Resource Mapping pioneer in Karnataka', 'Solar rooftop microgrid installed on campus', 'Recognized VTU R&D Centre'],
    accreditation: 'AICTE & Autonomous Approved',
    vtuResearchCenter: true
  },
  {
    id: 'ug-ece',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Electronics & Communication Engineering',
    departmentName: 'Department of Electronics & Communication Engineering',
    code: 'EC / E031 & E049',
    establishedYear: 1967,
    intake: 120,
    stream: 'Aided (60) & Un-Aided (60)',
    hodName: 'Dr. Mahabaleshwar S. K.',
    hodDesignation: 'Professor & Head (Dean R&D / ICT)',
    hodEmail: 'ece_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Recognized center of excellence in VLSI design, semiconductor devices, 5G wireless networks, embedded microcontrollers, and digital signal processing.',
    specializations: ['VLSI Semiconductor Design', '5G Wireless & Microwave Networks', 'Embedded Microcontrollers', 'Digital Signal & Image Processing'],
    keyLabs: ['Cadence VLSI Design Lab', 'Advanced Wireless & RF Lab', 'DSP & Microcontroller Workstation'],
    keyHighlights: ['Cadence & Synopsys EDA suites', 'Funded research projects from ISRO, AICTE & DST', 'Active IEEE Student Branch'],
    accreditation: 'NBA Accredited',
    vtuResearchCenter: true
  },
  {
    id: 'ug-automobile',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Automobile Engineering',
    departmentName: 'Department of Automobile Engineering',
    code: 'AU / E049',
    establishedYear: 1980,
    intake: 30,
    stream: 'Un-Aided (Re-established 2024-25)',
    hodName: 'Dr. C. M. Veerendrakumar',
    hodDesignation: 'Professor & Head',
    hodEmail: 'au_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Re-established in academic year 2024–25 with modern laboratories for automotive powertrain testing, electric vehicle architecture, vehicle chassis diagnostics, and emission compliance.',
    specializations: ['Electric Vehicle Battery & Powertrains', 'Automotive Chassis Dynamics', 'Engine Emission Diagnostics', 'Autonomous Vehicle Sensorics'],
    keyLabs: ['Automotive Chassis & Transmission Lab', 'EV Battery & Powertrain Testbed', 'Engine Diagnostics & Emission Lab'],
    keyHighlights: ['Formula Student racing prototype vehicle', 'Electric buggy design for campus commute', 'Testing facilities for regional transport corporations'],
    accreditation: 'AICTE Approved',
    vtuResearchCenter: true
  },
  {
    id: 'ug-cse',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Computer Science & Engineering',
    departmentName: 'Department of Computer Science & Engineering',
    code: 'CS / E031 & E049',
    establishedYear: 1983,
    intake: 180,
    stream: 'Aided (30) & Un-Aided (150)',
    hodName: 'Dr. S. V. Saboji',
    hodDesignation: 'Professor & Head',
    hodEmail: 'hod_cse@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'NBA accredited premier computing department delivering world-class curriculum in algorithm design, distributed computing, cloud architectures, and full-stack software development.',
    specializations: ['Distributed Systems & Cloud Architecture', 'Artificial Intelligence & Data Mining', 'Cybersecurity & Cryptography', 'High Performance Computing'],
    keyLabs: ['High Performance Computing Lab', 'Network Systems Lab', 'Full Stack Development Lab'],
    keyHighlights: ['NBA accredited department', 'Active ACM and CSI student chapters', 'Highest placement track record in tier-1 IT firms'],
    accreditation: 'NBA Accredited',
    vtuResearchCenter: true
  },
  {
    id: 'ug-ipe',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Industrial & Production Engineering',
    departmentName: 'Department of Industrial & Production Engineering',
    code: 'IP / E031',
    establishedYear: 1984,
    intake: 30,
    stream: 'Aided (30)',
    hodName: 'Dr. C. M. Javalagi',
    hodDesignation: 'Associate Professor & Head',
    hodEmail: 'ipe_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Focusing on supply chain optimization, Lean Six Sigma, industrial robotics, operational research, ergonomics, and Industry 4.0 automated manufacturing.',
    specializations: ['Industry 4.0 Factory Automation', 'Supply Chain Optimization', 'Lean Six Sigma & Quality Control', 'Operations Research & Ergonomics'],
    keyLabs: ['Flexible Manufacturing Systems (FMS) Lab', 'Quality Engineering & Metrology Lab', 'Ergonomics & Work Design Facility'],
    keyHighlights: ['Strong ties with manufacturing belts', 'Industry 4.0 demonstration setups', 'Pioneering work in operations research'],
    accreditation: 'AICTE & Autonomous Approved',
    vtuResearchCenter: true
  },
  {
    id: 'ug-ise',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Information Science & Engineering',
    departmentName: 'Department of Information Science & Engineering',
    code: 'IS / E049',
    establishedYear: 2000,
    intake: 180,
    stream: 'Un-Aided (180)',
    hodName: 'Dr. Lokesh B. B.',
    hodDesignation: 'Associate Professor & Head',
    hodEmail: 'ise_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Excellence in enterprise information systems, cybersecurity, data warehousing, cloud DevOps, software quality engineering, and mobile computing.',
    specializations: ['Enterprise Information Architecture', 'Cloud DevOps & Microservices', 'Data Warehousing & Business Intelligence', 'Cyber-Physical Systems Security'],
    keyLabs: ['Database Systems Lab', 'Software Testing & Automation Lab', 'Mobile App Development Center'],
    keyHighlights: ['Exceptional placement records', 'Collaborative hackathons with MNCs', 'Modern IoT & Web3 experimentation wing'],
    accreditation: 'AICTE & Autonomous Approved',
    vtuResearchCenter: true
  },
  {
    id: 'ug-biotechnology',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Biotechnology',
    departmentName: 'Department of Biotechnology',
    code: 'BT / E049',
    establishedYear: 2002,
    intake: 30,
    stream: 'Un-Aided (30)',
    hodName: 'Dr. Bharati S. Meti',
    hodDesignation: 'Professor & Head',
    hodEmail: 'bt_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Interdisciplinary department driving research in bioprocess engineering, bioinformatics, agricultural biotechnology, and microbial genomics.',
    specializations: ['Bioprocess & Bioreactor Engineering', 'Bioinformatics & Computational Genomics', 'Biofuel & Renewable Bioenergy', 'Plant Tissue Culture'],
    keyLabs: ['Bioreactor & Fermentation Lab', 'Plant Tissue Culture Lab', 'Molecular Biology & Genetics Lab'],
    keyHighlights: ['Biofuel Research & Information Centre (BRIC)', 'Patents on bio-pesticides and natural extracts', 'DST funded research projects'],
    accreditation: 'AICTE & Autonomous Approved',
    vtuResearchCenter: true
  },
  {
    id: 'ug-aiml',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Artificial Intelligence & Machine Learning',
    departmentName: 'Department of Artificial Intelligence & Machine Learning',
    code: 'AI / E049',
    establishedYear: 2021,
    intake: 60,
    stream: 'Un-Aided (60)',
    hodName: 'Dr. Bharati M. Reshmi',
    hodDesignation: 'Associate Professor & Head',
    hodEmail: 'aiml_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Pioneering intelligent autonomous systems, computer vision, natural language processing, deep learning algorithms, and high-performance computing with modern GPU facilities.',
    specializations: ['Deep Neural Networks & Transformers', 'Computer Vision & Autonomous Robotics', 'Natural Language Processing (NLP)', 'High Performance GPU Parallel Computing'],
    keyLabs: ['Deep Learning & Computer Vision Lab', 'Cloud Computing & Big Data Lab', 'NVIDIA GPU Cluster Facility'],
    keyHighlights: ['AICTE IDEA Lab Integration', 'Industry MOUs with AWS & Intel', 'Hackathon winning student teams'],
    accreditation: 'AICTE & Autonomous Approved',
    vtuResearchCenter: true
  },
  {
    id: 'ug-et',
    degree: 'B.E.',
    level: 'undergraduate',
    name: 'Electronics & Computer Engineering',
    departmentName: 'Department of Electronics & Computer Engineering',
    code: 'ET / E049',
    establishedYear: 2022,
    intake: 60,
    stream: 'Un-Aided (60)',
    hodName: 'Dr. Mahabaleshwar S. K.',
    hodDesignation: 'Professor & Program Head',
    hodEmail: 'et_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Convergence of electronic hardware design and advanced software engineering, preparing engineers for Edge AI, IoT sensors, firmware programming, and cyber-physical systems.',
    specializations: ['Embedded Edge AI & TinyML', 'IoT Sensor Mesh Networks', 'Firmware & Device Drivers', 'Cyber-Physical Hardware Systems'],
    keyLabs: ['Embedded Systems & Edge Computing Lab', 'IoT Sensor Network Lab', 'Digital Signal Processing Suite'],
    keyHighlights: ['Industry-aligned curriculum', 'Fast-growing branch with tech recruiters', 'Hands-on hardware accelerator modules'],
    accreditation: 'AICTE & Autonomous Approved',
    vtuResearchCenter: true
  },

  // ================= 6 POSTGRADUATE (PG) PROGRAMMES =================
  {
    id: 'pg-mba',
    degree: 'MBA',
    level: 'postgraduate',
    name: 'Master of Business Administration (MBA)',
    departmentName: 'Department of Management Studies (MBA)',
    code: 'KEA PGCET / KMAT Code B124',
    establishedYear: 2006,
    intake: 60,
    stream: 'KEA PGCET / Management Quota (60 Seats)',
    hodName: 'Dr. Vinod S. Puranik',
    hodDesignation: 'Professor & Head',
    hodEmail: 'mba_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Autonomous Master of Business Administration fostering business leadership, entrepreneurship, strategic marketing, financial engineering, and human resource management.',
    specializations: ['Financial Engineering & Banking', 'Strategic Marketing & E-Commerce', 'Human Resource Management', 'Business Analytics & Data Intelligence'],
    keyLabs: ['Business Analytics & FinTech Lab', 'Corporate Case Study Simulation Room'],
    keyHighlights: ['Active industry-institute interface', 'Executive CXO guest lecture series', 'Dedicated placement and entrepreneurship incubation'],
    accreditation: 'AICTE Approved',
    vtuResearchCenter: true
  },
  {
    id: 'pg-mca',
    degree: 'MCA',
    level: 'postgraduate',
    name: 'Master of Computer Applications (MCA)',
    departmentName: 'Department of Computer Applications (MCA)',
    code: 'KEA PGCET / KMAT Code C408',
    establishedYear: 2008,
    intake: 60,
    stream: 'KEA PGCET / Management Quota (60 Seats)',
    hodName: 'Prof. Sangamesh M. Magi',
    hodDesignation: 'Associate Professor & Head',
    hodEmail: 'mca_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Autonomous Master of Computer Applications imparting cutting-edge software engineering, database administration, cloud architecture, and full-stack enterprise web development.',
    specializations: ['Full-Stack Enterprise Web Engineering', 'Cloud Computing & Serverless Arch', 'Mobile Computing & Android Dev', 'Database Administration & DevOps'],
    keyLabs: ['Advanced Software Engineering Lab', 'Cloud & Mobile Application Lab'],
    keyHighlights: ['Hands-on capstone industry internships', 'High campus placement rate in tier-1 IT firms', 'Dedicated student coding club'],
    accreditation: 'AICTE Approved',
    vtuResearchCenter: true
  },
  {
    id: 'pg-mtech-structural',
    degree: 'M.Tech',
    level: 'postgraduate',
    name: 'M.Tech in Structural Engineering',
    departmentName: 'Department of Civil Engineering (PG Wing)',
    code: 'KEA PGCET / GATE Code T810',
    establishedYear: 1998,
    intake: 18,
    stream: 'Autonomous M.Tech (18 Seats)',
    hodName: 'Dr. S. H. Sanni',
    hodDesignation: 'Professor & Head (Civil) / BoS Chairman',
    hodEmail: 'cv_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Advanced autonomous master program offering specializations in seismic design, non-linear finite element structural analysis, tall building analysis, and bridge engineering.',
    specializations: ['Earthquake Resistant Design', 'Non-linear Finite Element Analysis (FEA)', 'High-Performance Concrete Dynamics', 'Bridge & Long-Span Structural Design'],
    keyLabs: ['Structural Dynamics & Shake Table Lab', 'Advanced CAD/CAE Finite Element Workstation'],
    keyHighlights: ['GATE/AICTE stipend eligible (₹12,400/mo)', 'Consultancy on national dams and bridges', 'Direct involvement in TEQIP research programs'],
    accreditation: 'AICTE & VTU Autonomous',
    vtuResearchCenter: true
  },
  {
    id: 'pg-mtech-geotechnical',
    degree: 'M.Tech',
    level: 'postgraduate',
    name: 'M.Tech in Geotechnical Engineering',
    departmentName: 'Department of Civil Engineering (PG Wing)',
    code: 'KEA PGCET / GATE Code T810',
    establishedYear: 2004,
    intake: 18,
    stream: 'Autonomous M.Tech (18 Seats)',
    hodName: 'Dr. S. H. Sanni',
    hodDesignation: 'Professor & Head (Civil) / BoS Chairman',
    hodEmail: 'cv_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Postgraduate curriculum focusing on deep foundation systems, soil dynamics, underground excavations, slope stability mitigation, and geo-environmental engineering.',
    specializations: ['Deep Foundation Engineering', 'Soil Dynamics & Liquefaction Mitigation', 'Underground Tunneling & Slope Stability', 'Geo-Environmental Waste Containment'],
    keyLabs: ['Advanced Geotechnical Testing Lab', 'Soil Mechanics Computer Aided Rig'],
    keyHighlights: ['GATE/AICTE stipend eligible', 'Testing and vetting for regional railway/highway projects', 'Recognized research publications'],
    accreditation: 'AICTE & VTU Autonomous',
    vtuResearchCenter: true
  },
  {
    id: 'pg-mtech-environmental',
    degree: 'M.Tech',
    level: 'postgraduate',
    name: 'M.Tech in Environmental Engineering',
    departmentName: 'Department of Civil Engineering (PG Wing)',
    code: 'KEA PGCET / GATE Code T810',
    establishedYear: 1998,
    intake: 18,
    stream: 'Autonomous M.Tech (18 Seats)',
    hodName: 'Dr. S. H. Sanni',
    hodDesignation: 'Professor & Head (Civil) / BoS Chairman',
    hodEmail: 'cv_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Comprehensive research training in municipal & industrial wastewater recycling, ambient air quality dispersion modeling, hazardous waste containment, and ecological impact audits.',
    specializations: ['Industrial Effluent Zero-Liquid Discharge', 'Atmospheric Dispersion & Air Quality', 'Hazardous Solid Waste Remediation', 'Environmental Impact Assessment (EIA)'],
    keyLabs: ['Environmental Quality Analysis Lab', 'Water & Wastewater Chemistry Facility'],
    keyHighlights: ['State Government recognized environmental testing hub', 'Corporate sponsored thesis projects', 'GATE/AICTE stipend eligible'],
    accreditation: 'AICTE & VTU Autonomous',
    vtuResearchCenter: true
  },
  {
    id: 'pg-mtech-machinedesign',
    degree: 'M.Tech',
    level: 'postgraduate',
    name: 'M.Tech in Machine Design',
    departmentName: 'Department of Mechanical Engineering (PG Wing)',
    code: 'KEA PGCET / GATE Code T810',
    establishedYear: 2002,
    intake: 18,
    stream: 'Autonomous M.Tech (18 Seats)',
    hodName: 'Dr. V. V. Kuppast',
    hodDesignation: 'Professor & Head (Mechanical & PG Machine Design)',
    hodEmail: 'me_hod@becbgk.edu',
    hodPhone: '08354-234060',
    description: 'Autonomous master specialization in continuum mechanics, mechanical vibrations, fatigue & fracture mechanics, advanced tribology, and computer-aided engineering simulation.',
    specializations: ['Mechanical Vibrations & Modal Analysis', 'Fracture Mechanics & Fatigue Prediction', 'Tribology & Contact Mechanics', 'Aeroelasticity & Composite Structure Design'],
    keyLabs: ['Advanced CAD/CAE Finite Element Suite', 'Vibration & Acoustic Analysis Lab'],
    keyHighlights: ['GATE/AICTE stipend eligible', 'High-end ANSYS/Abaqus multi-physics clusters', 'Sponsored projects with automotive R&D centres'],
    accreditation: 'AICTE & VTU Autonomous',
    vtuResearchCenter: true
  }
];

export interface DepartmentSummaryStats {
  totalUgCount: number;
  totalPgCount: number;
  totalDepartments: number;
  totalIntake: number;
  nbaAccreditedCount: number;
  vtuResearchCentresCount: number;
}

/**
 * Simulates fetching current academic departments and HOD directory data
 */
export async function fetchDepartmentDirectory(): Promise<{
  programmes: ProgrammeHOD[];
  leadership: LeadershipMember[];
  stats: DepartmentSummaryStats;
}> {
  // Simulate network fetch with small delay
  await new Promise((resolve) => setTimeout(resolve, 200));

  const totalUg = BEC_PROGRAMMES_HODS.filter(p => p.level === 'undergraduate').length;
  const totalPg = BEC_PROGRAMMES_HODS.filter(p => p.level === 'postgraduate').length;
  const totalIntake = BEC_PROGRAMMES_HODS.reduce((sum, p) => sum + (p.intake || 0), 0);

  return {
    programmes: BEC_PROGRAMMES_HODS,
    leadership: INSTITUTIONAL_LEADERSHIP,
    stats: {
      totalUgCount: totalUg, // 11
      totalPgCount: totalPg, // 6
      totalDepartments: totalUg + totalPg, // 17
      totalIntake,
      nbaAccreditedCount: 4,
      vtuResearchCentresCount: 10
    }
  };
}
